CTORATstpSPFensUserInfoField = {
    "LogInAccount": "string",
    "LogInAccountType": "char",
}

CTORATstpSPConnectionInfoField = {
    "InnerIPAddress": "string",
    "InnerPort": "int",
    "OuterIPAddress": "string",
    "OuterPort": "int",
    "MacAddress": "string",
}

CTORATstpSPReqUserLoginField = {
    "LogInAccount": "string",
    "LogInAccountType": "char",
    "Password": "string",
    "UserProductInfo": "string",
    "ProtocolInfo": "string",
    "MacAddress": "string",
    "OneTimePassword": "string",
    "InnerIPAddress": "string",
    "Lang": "char",
    "TerminalInfo": "string",
    "GWMacAddress": "string",
    "GWInnerIPAddress": "string",
    "GWOuterIPAddress": "string",
    "DepartmentID": "string",
    "HDSerial": "string",
    "AuthMode": "char",
    "DeviceID": "string",
    "CertSerial": "string",
    "Mobile": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
    "DeviceType": "char",
}

CTORATstpSPRspUserLoginField = {
    "LoginTime": "string",
    "LogInAccount": "string",
    "LogInAccountType": "char",
    "SystemName": "string",
    "FrontID": "int",
    "SessionID": "int",
    "MaxOrderRef": "int",
    "PrivateFlowCount": "int",
    "PublicFlowCount": "int",
    "RequestID": "int",
    "TradingDay": "string",
    "UserID": "string",
    "UserName": "string",
    "UserType": "char",
    "DepartmentID": "string",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "HDSerial": "string",
    "OrderInsertCommFlux": "int",
    "OrderActionCommFlux": "int",
    "Mobile": "string",
    "PasswordUpdatePeriod": "int",
    "PasswordRemainDays": "int",
    "NeedUpdatePassword": "int",
    "SSEOrderInsertCommFlux": "int",
    "SSEOrderActionCommFlux": "int",
    "SZSEOrderInsertCommFlux": "int",
    "SZSEOrderActionCommFlux": "int",
    "OuterIPAddress": "string",
    "OuterPort": "int",
    "CertSerial": "string",
}

CTORATstpSPRspInfoField = {
    "ErrorID": "int",
    "ErrorMsg": "string",
}

CTORATstpSPUserLogoutField = {
    "UserID": "string",
}

CTORATstpSPUserPasswordUpdateField = {
    "UserID": "string",
    "OldPassword": "string",
    "NewPassword": "string",
}

CTORATstpSPReqInputDeviceSerialField = {
    "UserID": "string",
    "DeviceID": "string",
    "CertSerial": "string",
    "DeviceType": "char",
}

CTORATstpSPRspInputDeviceSerialField = {
    "RequestID": "int",
    "UserID": "string",
}

CTORATstpSPInputOrderField = {
    "SecurityID": "string",
    "OrderRef": "int",
    "OrderPriceType": "char",
    "Direction": "char",
    "CombOffsetFlag": "string",
    "CombHedgeFlag": "string",
    "LimitPrice": "double",
    "VolumeTotalOriginal": "int",
    "TimeCondition": "char",
    "VolumeCondition": "char",
    "MinVolume": "int",
    "ForceCloseReason": "char",
    "UserForceClose": "int",
    "InvestorID": "string",
    "ExchangeID": "char",
    "ShareholderID": "string",
    "BusinessUnitID": "string",
    "AccountID": "string",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "OrderSysID": "string",
    "TerminalInfo": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "CondCheck": "char",
    "ExchangeCombID": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPOrderField = {
    "TradingDay": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "FrontID": "int",
    "SessionID": "int",
    "OrderRef": "int",
    "OrderSysID": "string",
    "PbuID": "string",
    "OrderLocalID": "string",
    "OrderPriceType": "char",
    "Direction": "char",
    "CombOffsetFlag": "string",
    "CombHedgeFlag": "string",
    "Price": "double",
    "VolumeTotalOriginal": "int",
    "TimeCondition": "char",
    "VolumeCondition": "char",
    "MinVolume": "int",
    "RequestID": "int",
    "MarketID": "char",
    "ShareholderID": "string",
    "OrderOperateStatus": "char",
    "OrderStatus": "char",
    "VolumeTraded": "int",
    "InsertDate": "string",
    "InsertTime": "string",
    "AcceptTime": "string",
    "CancelTime": "string",
    "InvestorID": "string",
    "StatusMsg": "string",
    "UserForceClose": "int",
    "InsertUserID": "string",
    "CancelUserID": "string",
    "BusinessUnitID": "string",
    "DepartmentID": "string",
    "AccountID": "string",
    "CurrencyID": "char",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "ForceCloseReason": "char",
    "TerminalInfo": "string",
    "Operway": "char",
    "HDSerial": "string",
    "VolumeCanceled": "int",
    "ExchangeCombID": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
    "TradeAmount": "double",
}

CTORATstpSPUserRefField = {
    "UserID": "string",
}

CTORATstpSPInputOrderActionField = {
    "InvestorID": "string",
    "OrderActionRef": "int",
    "OrderRef": "int",
    "FrontID": "int",
    "SessionID": "int",
    "ExchangeID": "char",
    "OrderSysID": "string",
    "OrderActionFlag": "char",
    "SecurityID": "string",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "CancelOrderLocalID": "string",
    "TerminalInfo": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPTradeField = {
    "InvestorID": "string",
    "SecurityID": "string",
    "InsertUserID": "string",
    "ExchangeID": "char",
    "TradeID": "string",
    "Direction": "char",
    "OrderSysID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "OffsetFlag": "char",
    "HedgeFlag": "char",
    "Price": "double",
    "Volume": "int",
    "TradeDate": "string",
    "TradeTime": "string",
    "PbuID": "string",
    "OrderLocalID": "string",
    "TradingDay": "string",
    "BusinessUnitID": "string",
    "AccountID": "string",
    "CurrencyID": "char",
    "OrderRef": "int",
    "DepartmentID": "string",
}

CTORATstpSPInputExerciseField = {
    "InvestorID": "string",
    "SecurityID": "string",
    "ExerciseRef": "int",
    "Volume": "int",
    "BusinessUnitID": "string",
    "ExerciseType": "char",
    "ExchangeID": "char",
    "ShareholderID": "string",
    "AccountID": "string",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "ExerciseSysID": "string",
    "TerminalInfo": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPExerciseField = {
    "TradingDay": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "FrontID": "int",
    "SessionID": "int",
    "ExerciseRef": "int",
    "ExerciseSysID": "string",
    "PbuID": "string",
    "ExerciseLocalID": "string",
    "ExerciseType": "char",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "Volume": "int",
    "VolumeCanceled": "int",
    "MarketID": "char",
    "ShareholderID": "string",
    "ShareholderIDType": "char",
    "DepartmentID": "string",
    "AccountID": "string",
    "CurrencyID": "char",
    "ExerciseStatus": "char",
    "ExerciseOperateStatus": "char",
    "StatusMsg": "string",
    "ErrorID": "int",
    "BranchID": "string",
    "InsertUserID": "string",
    "InsertDate": "string",
    "InsertTime": "string",
    "InsertMillisec": "int",
    "AcceptTime": "string",
    "CancelTime": "string",
    "CancelUserID": "string",
    "StockPositionExerciseSerial": "int",
    "StockPositionSerial": "int",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "RequestID": "int",
    "TerminalInfo": "string",
    "RecordNumber": "int",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "Mobile": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPInputExerciseActionField = {
    "InvestorID": "string",
    "ExerciseActionRef": "int",
    "ExerciseRef": "int",
    "FrontID": "int",
    "SessionID": "int",
    "ExchangeID": "char",
    "ExerciseSysID": "string",
    "ExerciseActionFlag": "char",
    "SecurityID": "string",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "CancelExerciseLocalID": "string",
    "TerminalInfo": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPInputLockField = {
    "SecurityID": "string",
    "LockRef": "int",
    "LockType": "char",
    "Volume": "int",
    "InvestorID": "string",
    "ExchangeID": "char",
    "ShareholderID": "string",
    "BusinessUnitID": "string",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "TerminalInfo": "string",
    "LockSysID": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPLockField = {
    "TradingDay": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "FrontID": "int",
    "SessionID": "int",
    "LockRef": "int",
    "LockSysID": "string",
    "PbuID": "string",
    "LockLocalID": "string",
    "LockType": "char",
    "Volume": "int",
    "VolumeCanceled": "int",
    "RequestID": "int",
    "MarketID": "char",
    "ShareholderID": "string",
    "ShareholderIDType": "char",
    "LockStatus": "char",
    "InsertDate": "string",
    "InsertTime": "string",
    "AcceptTime": "string",
    "CancelTime": "string",
    "BranchID": "string",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "ErrorID": "int",
    "StatusMsg": "string",
    "InsertUserID": "string",
    "CancelUserID": "string",
    "StockPositionLockSerial": "int",
    "StockPositionSerial": "int",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "TerminalInfo": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "RecordNumber": "int",
    "Operway": "char",
    "HDSerial": "string",
    "Mobile": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPInputLockActionField = {
    "InvestorID": "string",
    "LockActionRef": "int",
    "LockRef": "int",
    "FrontID": "int",
    "SessionID": "int",
    "ExchangeID": "char",
    "LockSysID": "string",
    "LockActionFlag": "char",
    "SecurityID": "string",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "CancelLockLocalID": "string",
    "TerminalInfo": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPStockDisposalField = {
    "TradingDay": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "FrontID": "int",
    "SessionID": "int",
    "StockDisposalRef": "int",
    "StockDisposalSysID": "string",
    "PbuID": "string",
    "StockDisposalLocalID": "string",
    "StockDisposalType": "char",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "Volume": "int",
    "VolumeCanceled": "int",
    "MarketID": "char",
    "ShareholderID": "string",
    "ShareholderIDType": "char",
    "DepartmentID": "string",
    "StockDisposalStatus": "char",
    "StockDisposalOperateStatus": "char",
    "StatusMsg": "string",
    "ErrorID": "int",
    "BranchID": "string",
    "InsertUserID": "string",
    "InsertDate": "string",
    "InsertTime": "string",
    "InsertMillisec": "int",
    "AcceptTime": "string",
    "CancelTime": "string",
    "CancelUserID": "string",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "RequestID": "int",
    "TerminalInfo": "string",
    "RecordNumber": "int",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "Mobile": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPInputCombOrderField = {
    "SecurityID": "string",
    "CombOrderRef": "int",
    "CombinationStrategy": "char",
    "CombDirection": "char",
    "ExchangeCombID": "string",
    "Volume": "int",
    "InvestorID": "string",
    "ExchangeID": "char",
    "ShareholderID": "string",
    "BusinessUnitID": "string",
    "AccountID": "string",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "TerminalInfo": "string",
    "CombOrderSysID": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPCombOrderField = {
    "TradingDay": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "CombinationStrategy": "char",
    "CombDirection": "char",
    "FrontID": "int",
    "SessionID": "int",
    "CombOrderRef": "int",
    "CombOrderSysID": "string",
    "PbuID": "string",
    "CombOrderLocalID": "string",
    "Volume": "int",
    "VolumeCanceled": "int",
    "RequestID": "int",
    "MarketID": "char",
    "ShareholderID": "string",
    "ShareholderIDType": "char",
    "CombOrderStatus": "char",
    "CombOrderOperateStatus": "char",
    "DepartmentID": "string",
    "AccountID": "string",
    "CurrencyID": "char",
    "ExchangeCombID": "string",
    "InsertDate": "string",
    "InsertTime": "string",
    "InsertMillisec": "int",
    "AcceptTime": "string",
    "CancelTime": "string",
    "BranchID": "string",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "ErrorID": "int",
    "StatusMsg": "string",
    "InsertUserID": "string",
    "CancelUserID": "string",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "TerminalInfo": "string",
    "RecordNumber": "int",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "Mobile": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPInputCombOrderActionField = {
    "InvestorID": "string",
    "CombOrderActionRef": "int",
    "CombOrderRef": "int",
    "FrontID": "int",
    "SessionID": "int",
    "ExchangeID": "char",
    "CombOrderSysID": "string",
    "CombOrderActionFlag": "char",
    "SecurityID": "string",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "CancelCombOrderLocalID": "string",
    "TerminalInfo": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPInputCondOrderField = {
    "SecurityID": "string",
    "CondOrderRef": "int",
    "OrderPriceType": "char",
    "Direction": "char",
    "CombOffsetFlag": "string",
    "CombHedgeFlag": "string",
    "LimitPrice": "double",
    "VolumeTotalOriginal": "int",
    "TimeCondition": "char",
    "VolumeCondition": "char",
    "MinVolume": "int",
    "ForceCloseReason": "char",
    "UserForceClose": "int",
    "InvestorID": "string",
    "ExchangeID": "char",
    "ShareholderID": "string",
    "BusinessUnitID": "string",
    "AccountID": "string",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "CondOrderID": "int",
    "TerminalInfo": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "OrderVolumeType": "char",
    "ContingentCondition": "char",
    "ConditionPrice": "double",
    "PriceTicks": "int",
    "VolumeMultiple": "int",
    "RelativeFrontID": "int",
    "RelativeSessionID": "int",
    "RelativeParam": "string",
    "AppendContingentCondition": "char",
    "AppendConditionPrice": "double",
    "AppendRelativeFrontID": "int",
    "AppendRelativeSessionID": "int",
    "AppendRelativeParam": "string",
    "Operway": "char",
    "HDSerial": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPConditionOrderField = {
    "TradingDay": "string",
    "SecurityID": "string",
    "CondOrderRef": "int",
    "OrderPriceType": "char",
    "Direction": "char",
    "CombOffsetFlag": "string",
    "CombHedgeFlag": "string",
    "LimitPrice": "double",
    "VolumeTotalOriginal": "int",
    "TimeCondition": "char",
    "VolumeCondition": "char",
    "MinVolume": "int",
    "ForceCloseReason": "char",
    "RequestID": "int",
    "UserForceClose": "int",
    "InvestorID": "string",
    "ExchangeID": "char",
    "ShareholderID": "string",
    "BusinessUnitID": "string",
    "AccountID": "string",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "CondOrderID": "int",
    "TerminalInfo": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "OrderVolumeType": "char",
    "ContingentCondition": "char",
    "ConditionPrice": "double",
    "PriceTicks": "int",
    "VolumeMultiple": "int",
    "RelativeFrontID": "int",
    "RelativeSessionID": "int",
    "RelativeParam": "string",
    "AppendContingentCondition": "char",
    "AppendConditionPrice": "double",
    "AppendRelativeFrontID": "int",
    "AppendRelativeSessionID": "int",
    "AppendRelativeParam": "string",
    "FrontID": "int",
    "SessionID": "int",
    "DepartmentID": "string",
    "CondOrderStatus": "char",
    "StatusMsg": "string",
    "InsertUserID": "string",
    "InsertDate": "string",
    "InsertTime": "string",
    "InsertMillisec": "int",
    "CancelTime": "string",
    "CancelUserID": "string",
    "ActiveTime": "string",
    "Operway": "char",
    "HDSerial": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPInputCondOrderActionField = {
    "ExchangeID": "char",
    "CondOrderActionRef": "int",
    "CondOrderRef": "int",
    "FrontID": "int",
    "SessionID": "int",
    "CondOrderID": "int",
    "OrderActionFlag": "char",
    "InvestorID": "string",
    "SecurityID": "string",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "CancelCondOrderID": "int",
    "TerminalInfo": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPInputCombExerciseField = {
    "InvestorID": "string",
    "CallSecurityID": "string",
    "PutSecurityID": "string",
    "CombExerciseRef": "int",
    "Volume": "int",
    "BusinessUnitID": "string",
    "ExchangeID": "char",
    "ShareholderID": "string",
    "AccountID": "string",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "CombExerciseSysID": "string",
    "TerminalInfo": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPCombExerciseField = {
    "TradingDay": "string",
    "ExchangeID": "char",
    "CallSecurityID": "string",
    "PutSecurityID": "string",
    "FrontID": "int",
    "SessionID": "int",
    "CombExerciseRef": "int",
    "CombExerciseSysID": "string",
    "PbuID": "string",
    "CombExerciseLocalID": "string",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "Volume": "int",
    "VolumeCanceled": "int",
    "MarketID": "char",
    "ShareholderID": "string",
    "ShareholderIDType": "char",
    "DepartmentID": "string",
    "AccountID": "string",
    "CurrencyID": "char",
    "ExerciseStatus": "char",
    "ExerciseOperateStatus": "char",
    "StatusMsg": "string",
    "ErrorID": "int",
    "BranchID": "string",
    "InsertUserID": "string",
    "InsertDate": "string",
    "InsertTime": "string",
    "InsertMillisec": "int",
    "AcceptTime": "string",
    "CancelTime": "string",
    "CancelUserID": "string",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "RequestID": "int",
    "TerminalInfo": "string",
    "RecordNumber": "int",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "Mobile": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPInputCombExerciseActionField = {
    "InvestorID": "string",
    "CombExerciseActionRef": "int",
    "CombExerciseRef": "int",
    "FrontID": "int",
    "SessionID": "int",
    "ExchangeID": "char",
    "CombExerciseSysID": "string",
    "ExerciseActionFlag": "char",
    "CallSecurityID": "string",
    "PutSecurityID": "string",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "CancelCombExerciseLocalID": "string",
    "TerminalInfo": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPReqInquiryMaxLockVolumeField = {
    "InvestorID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
}

CTORATstpSPRspInquiryMaxLockVolumeField = {
    "InvestorID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "Volume": "int",
    "RequestID": "int",
}

CTORATstpSPReqInquiryMaxCoverVolumeField = {
    "InvestorID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
}

CTORATstpSPRspInquiryMaxCoverVolumeField = {
    "InvestorID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "Volume": "int",
    "RequestID": "int",
}

CTORATstpSPReqInquirySplitCombMarginDifferenceField = {
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "ExchangeID": "char",
    "CombSecurityID": "string",
    "ExchangeCombID": "string",
    "ShareholderID": "string",
    "CombinationStrategy": "char",
    "Volume": "int",
}

CTORATstpSPRspInquirySplitCombMarginDifferenceField = {
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "ExchangeID": "char",
    "CombSecurityID": "string",
    "ExchangeCombID": "string",
    "ShareholderID": "string",
    "CombinationStrategy": "char",
    "Volume": "int",
    "RequestID": "int",
    "LeftLegPosMargin": "double",
    "LeftLegPosLiveMargin": "double",
    "RightLegPosMargin": "double",
    "RightLegPosLiveMargin": "double",
    "CombPosMargin": "double",
    "CombPosLiveMargin": "double",
    "MarginDifference": "double",
    "LiveMarginDifference": "double",
}

CTORATstpSPInputTransferFundField = {
    "ApplySerial": "int",
    "AccountID": "string",
    "CurrencyID": "char",
    "TransferDirection": "char",
    "Amount": "double",
    "DepartmentID": "string",
    "TradingAccountPassword": "string",
    "BankID": "char",
    "BankAccountPassword": "string",
}

CTORATstpSPTransferFundField = {
    "FundSerial": "int",
    "ApplySerial": "int",
    "FrontID": "int",
    "SessionID": "int",
    "AccountID": "string",
    "CurrencyID": "char",
    "TransferDirection": "char",
    "Amount": "double",
    "TransferStatus": "char",
    "OperatorID": "string",
    "OperateDate": "string",
    "OperateTime": "string",
    "DepartmentID": "string",
    "BankAccountID": "string",
    "BankID": "char",
}

CTORATstpSPTransferPositionField = {
    "PositionSerial": "int",
    "ApplySerial": "int",
    "FrontID": "int",
    "SessionID": "int",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "ExchangeID": "char",
    "ShareholderID": "string",
    "MarketID": "char",
    "PosiDirection": "char",
    "HedgeFlag": "char",
    "SecurityID": "string",
    "TradingDay": "string",
    "TransferDirection": "char",
    "TransferPositionType": "char",
    "HistoryVolume": "int",
    "TodayVolume": "int",
    "TransferStatus": "char",
    "OperatorID": "string",
    "OperateDate": "string",
    "OperateTime": "string",
}

CTORATstpSPInputTransferPositionField = {
    "ApplySerial": "int",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "SecurityID": "string",
    "TransferDirection": "char",
    "Volume": "int",
    "TransferPositionType": "char",
    "PosiDirection": "char",
    "HedgeFlag": "char",
    "RequestID": "int",
}

CTORATstpSPInputTransferStockPositionField = {
    "ApplySerial": "int",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "SecurityID": "string",
    "SPStockTransferReason": "char",
    "Volume": "int",
    "TransferPositionType": "char",
}

CTORATstpSPTransferStockPositionField = {
    "PositionSerial": "int",
    "ApplySerial": "int",
    "FrontID": "int",
    "SessionID": "int",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "ExchangeID": "char",
    "ShareholderID": "string",
    "MarketID": "char",
    "SecurityID": "string",
    "TradingDay": "string",
    "SPStockTransferReason": "char",
    "TransferPositionType": "char",
    "HistoryVolume": "int",
    "TodayBSVolume": "int",
    "TodayPRVolume": "int",
    "TransferStatus": "char",
    "OperatorID": "string",
    "OperateDate": "string",
    "OperateTime": "string",
}

CTORATstpSPReqInquiryJZFundField = {
    "AccountID": "string",
    "CurrencyID": "char",
    "DepartmentID": "string",
}

CTORATstpSPRspInquiryJZFundField = {
    "AccountID": "string",
    "CurrencyID": "char",
    "UsefulMoney": "double",
    "FetchLimit": "double",
    "RequestID": "int",
    "DepartmentID": "string",
}

CTORATstpSPReqInquiryBankAccountFundField = {
    "AccountID": "string",
    "CurrencyID": "char",
    "DepartmentID": "string",
    "BankAccountPassword": "string",
}

CTORATstpSPRspInquiryBankAccountFundField = {
    "AccountID": "string",
    "CurrencyID": "char",
    "Balance": "double",
    "RequestID": "int",
    "DepartmentID": "string",
    "BankID": "char",
    "BankAccountID": "string",
}

CTORATstpSPReqInquiryStockPositionField = {
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "TradingDay": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
}

CTORATstpSPRspInquiryStockPositionField = {
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "TradingDay": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "HistoryPos": "int",
    "HistoryPosFrozen": "int",
    "TodayBSPos": "int",
    "TodayBSPosFrozen": "int",
    "TodayPRPos": "int",
    "TodayPRPosFrozen": "int",
    "TodaySMPos": "int",
    "TodaySMPosFrozen": "int",
    "HistoryPosCost": "double",
    "TotalPosCost": "double",
    "MarginBuyPos": "int",
    "ShortSellPos": "int",
    "TodayShortSellPos": "int",
    "PrePosition": "int",
    "AvailablePosition": "int",
    "CurrentPosition": "int",
    "RequestID": "int",
}

CTORATstpSPSpecificSecurityField = {
    "ExchangeID": "char",
    "SecurityID": "string",
}

CTORATstpSPMarketDataField = {
    "SecurityID": "string",
    "ExchangeID": "char",
    "TradingDay": "string",
    "SecurityName": "string",
    "PreClosePrice": "double",
    "OpenPrice": "double",
    "UpperLimitPrice": "double",
    "LowerLimitPrice": "double",
    "Volume": "long long",
    "Turnover": "double",
    "TradingCount": "long long",
    "LastPrice": "double",
    "ClosePrice": "double",
    "HighestPrice": "double",
    "LowestPrice": "double",
    "PERatio1": "double",
    "PERatio2": "double",
    "PriceUpDown1": "double",
    "PriceUpDown2": "double",
    "OpenInterest": "double",
    "BidPrice1": "double",
    "AskPrice1": "double",
    "BidVolume1": "long long",
    "AskVolume1": "long long",
    "BidPrice2": "double",
    "BidVolume2": "long long",
    "AskPrice2": "double",
    "AskVolume2": "long long",
    "BidPrice3": "double",
    "BidVolume3": "long long",
    "AskPrice3": "double",
    "AskVolume3": "long long",
    "BidPrice4": "double",
    "BidVolume4": "long long",
    "AskPrice4": "double",
    "AskVolume4": "long long",
    "BidPrice5": "double",
    "BidVolume5": "long long",
    "AskPrice5": "double",
    "AskVolume5": "long long",
    "UpdateTime": "string",
    "UpdateMillisec": "int",
    "MDSecurityStat": "char",
    "SettlementPrice": "double",
}

CTORATstpSPMarketStatusField = {
    "MarketID": "char",
    "MarketStatus": "char",
}

CTORATstpSPTradingNoticeField = {
    "NoticeSerial": "string",
    "InsertDate": "string",
    "InsertTime": "string",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "Content": "string",
    "OperatorID": "string",
}

CTORATstpSPQryExchangeField = {
    "ExchangeID": "char",
}

CTORATstpSPExchangeField = {
    "ExchangeID": "char",
    "ExchangeName": "string",
    "TradingDay": "string",
    "DataSyncStatus": "char",
}

CTORATstpSPQryMarketDataField = {
    "SecurityID": "string",
    "ExchangeID": "char",
}

CTORATstpSPQrySecurityField = {
    "SecurityID": "string",
    "ExchangeID": "char",
}

CTORATstpSPSecurityField = {
    "ExchangeID": "char",
    "SecurityID": "string",
    "ExchSecurityID": "string",
    "SecurityName": "string",
    "UnderlyingSecurityID": "string",
    "UnderlyingSecurityName": "string",
    "UnderlyingMultiple": "int",
    "StrikeMode": "char",
    "OptionsType": "char",
    "MarketID": "char",
    "ProductID": "char",
    "SecurityType": "char",
    "OrderUnit": "char",
    "BuyTradingUnit": "int",
    "SellTradingUnit": "int",
    "MaxMarketOrderBuyVolume": "int",
    "MinMarketOrderBuyVolume": "int",
    "MaxLimitOrderBuyVolume": "int",
    "MinLimitOrderBuyVolume": "int",
    "MaxMarketOrderSellVolume": "int",
    "MinMarketOrderSellVolume": "int",
    "MaxLimitOrderSellVolume": "int",
    "MinLimitOrderSellVolume": "int",
    "VolumeMultiple": "int",
    "PriceTick": "double",
    "PositionType": "char",
    "SecurityStatus": "int",
    "StrikePrice": "double",
    "FirstDate": "string",
    "LastDate": "string",
    "StrikeDate": "string",
    "ExpireDate": "string",
    "DelivDate": "string",
    "IsUpDownLimit": "int",
    "MarginUnit": "double",
    "PreSettlementPrice": "double",
    "PreClosePrice": "double",
    "UnderlyingPreClosePrice": "double",
    "PreOpenInterest": "int",
    "MaxQuoteOrderBuyVolume": "int",
    "MinQuoteOrderBuyVolume": "int",
    "MaxQuoteOrderSellVolume": "int",
    "MinQuoteOrderSellVolume": "int",
    "UpperLimitPrice": "double",
    "LowerLimitPrice": "double",
}

CTORATstpSPQryBUProxyField = {
    "InvestorID": "string",
    "UserID": "string",
    "BusinessUnitID": "string",
}

CTORATstpSPBUProxyField = {
    "InvestorID": "string",
    "UserID": "string",
    "BusinessUnitID": "string",
    "DepartmentID": "string",
}

CTORATstpSPQryUserField = {
    "UserID": "string",
    "UserType": "char",
}

CTORATstpSPUserField = {
    "UserID": "string",
    "UserName": "string",
    "UserType": "char",
    "DepartmentID": "string",
    "LoginLimit": "int",
    "PasswordFailLimit": "int",
    "Status": "char",
    "Contacter": "string",
    "Fax": "string",
    "Telephone": "string",
    "Email": "string",
    "Address": "string",
    "ZipCode": "string",
    "OpenDate": "string",
    "CloseDate": "string",
    "OrderInsertCommFlux": "int",
    "OrderActionCommFlux": "int",
    "SSEOrderInsertCommFlux": "int",
    "SSEOrderActionCommFlux": "int",
    "SZSEOrderInsertCommFlux": "int",
    "SZSEOrderActionCommFlux": "int",
}

CTORATstpSPQryInvestorField = {
    "InvestorID": "string",
}

CTORATstpSPInvestorField = {
    "InvestorID": "string",
    "DepartmentID": "string",
    "InvestorType": "char",
    "InvestorName": "string",
    "IdCardType": "char",
    "IdCardNo": "string",
    "ContractNo": "string",
    "OpenDate": "string",
    "CloseDate": "string",
    "TradeStatus": "char",
    "Reserve1": "string",
    "InvestorLevel": "char",
    "Mobile": "string",
    "Telephone": "string",
    "Email": "string",
    "Fax": "string",
    "Address": "string",
    "ZipCode": "string",
    "Reserve2": "string",
    "Operways": "string",
    "ActiveStatus": "char",
    "LoginLimit": "int",
    "MarginFetchRatio": "double",
}

CTORATstpSPQryShareholderAccountField = {
    "InvestorID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "ShareholderIDType": "char",
}

CTORATstpSPShareholderAccountField = {
    "InvestorID": "string",
    "ExchangeID": "char",
    "ShareholderID": "string",
    "ShareholderIDType": "char",
    "MarketID": "char",
}

CTORATstpSPQryTradingAccountField = {
    "InvestorID": "string",
    "CurrencyID": "char",
    "AccountID": "string",
    "AccountType": "char",
    "DepartmentID": "string",
}

CTORATstpSPTradingAccountField = {
    "DepartmentID": "string",
    "AccountID": "string",
    "CurrencyID": "char",
    "AccountType": "char",
    "PreDeposit": "double",
    "PreFrozenCash": "double",
    "UsefulMoney": "double",
    "FetchLimit": "double",
    "Deposit": "double",
    "Withdraw": "double",
    "FrozenMargin": "double",
    "FrozenCash": "double",
    "FrozenCommission": "double",
    "CurrMargin": "double",
    "Commission": "double",
    "RoyaltyIn": "double",
    "RoyaltyOut": "double",
    "AccountOwner": "string",
    "BankAccountID": "string",
    "BankID": "char",
    "ExcerciseFrozen": "double",
    "RiskLivePercent": "double",
    "RiskLiveLevel": "char",
    "LiveUsefulMoney": "double",
}

CTORATstpSPQryOrderField = {
    "InvestorID": "string",
    "SecurityID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "OrderSysID": "string",
    "InsertTimeStart": "string",
    "InsertTimeEnd": "string",
    "BusinessUnitID": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "ExchangeCombID": "string",
}

CTORATstpSPQryTradeField = {
    "InvestorID": "string",
    "SecurityID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "TradeID": "string",
    "TradeTimeStart": "string",
    "TradeTimeEnd": "string",
    "BusinessUnitID": "string",
}

CTORATstpSPQryPositionField = {
    "InvestorID": "string",
    "SecurityID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "BusinessUnitID": "string",
    "PosiDirection": "char",
    "HedgeFlag": "char",
}

CTORATstpSPPositionField = {
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "TradingDay": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "PosiDirection": "char",
    "HedgeFlag": "char",
    "HistoryPos": "int",
    "HistoryPosFrozen": "int",
    "TodayPos": "int",
    "TodayPosFrozen": "int",
    "TotalPosCost": "double",
    "LongFrozen": "int",
    "ShortFrozen": "int",
    "LongFrozenAmount": "double",
    "ShortFrozenAmount": "double",
    "OpenVolume": "int",
    "CloseVolume": "int",
    "OpenAmount": "double",
    "CloseAmount": "double",
    "Margin": "double",
    "FrozenMargin": "double",
    "FrozenCash": "double",
    "FrozenCommission": "double",
    "CashIn": "double",
    "Commission": "double",
    "StrikeFrozen": "int",
    "StrikeFrozenAmount": "double",
    "PrePosition": "int",
    "LastPrice": "double",
    "HistoryCombPos": "int",
    "TodayCombPos": "int",
    "HistoryCombPosSplitFrozen": "int",
    "TodayCombPosSplitFrozen": "int",
    "HistoryPosCombFrozen": "int",
    "TodayPosCombFrozen": "int",
    "OpenPosCost": "double",
    "PreCloseProfit": "double",
    "TodayCloseProfit": "double",
    "UnderlyingMultiple": "int",
    "BuyQuotaUsed": "double",
}

CTORATstpSPQryTradingFeeField = {
    "ExchangeID": "char",
}

CTORATstpSPTradingFeeField = {
    "ExchangeID": "char",
    "ProductID": "char",
    "SecurityType": "char",
    "SecurityID": "string",
    "BusinessClass": "char",
    "SystemFlag": "char",
    "StampTaxRatioByAmt": "double",
    "StampTaxRatioByPar": "double",
    "StampTaxFeeByVolume": "double",
    "StampTaxFeePerOrder": "double",
    "StampTaxFeeMin": "double",
    "StampTaxFeeMax": "double",
    "TransferRatioByAmt": "double",
    "TransferRatioByPar": "double",
    "TransferFeePerOrder": "double",
    "TransferFeeByVolume": "double",
    "TransferFeeMin": "double",
    "TransferFeeMax": "double",
    "HandlingRatioByAmt": "double",
    "HandlingRatioByPar": "double",
    "HandlingFeePerOrder": "double",
    "HandlingFeeByVolume": "double",
    "HandlingFeeMin": "double",
    "HandlingFeeMax": "double",
    "RegulateRatioByAmt": "double",
    "RegulateRatioByPar": "double",
    "RegulateFeeByVolume": "double",
    "RegulateFeePerOrder": "double",
    "RegulateFeeMin": "double",
    "RegulateFeeMax": "double",
    "SettlementRatioByAmt": "double",
    "SettlementRatioByPar": "double",
    "SettlementFeePerOrder": "double",
    "SettlementFeeByVolume": "double",
    "SettlementFeeMin": "double",
    "SettlementFeeMax": "double",
}

CTORATstpSPQryInvestorTradingFeeField = {
    "InvestorID": "string",
    "ExchangeID": "char",
    "DepartmentID": "string",
}

CTORATstpSPInvestorTradingFeeField = {
    "DepartmentID": "string",
    "InvestorID": "string",
    "ExchangeID": "char",
    "ProductID": "char",
    "SecurityType": "char",
    "SecurityID": "string",
    "BusinessClass": "char",
    "BrokerageType": "char",
    "RatioByAmt": "double",
    "RatioByPar": "double",
    "FeePerOrder": "double",
    "FeeMin": "double",
    "FeeMax": "double",
    "FeeByVolume": "double",
}

CTORATstpSPQryInvestorMarginFeeField = {
    "InvestorID": "string",
    "ExchangeID": "char",
    "DepartmentID": "string",
    "ProductID": "char",
    "SecurityType": "char",
    "BusinessClass": "char",
    "SecurityID": "string",
}

CTORATstpSPInvestorMarginFeeField = {
    "DepartmentID": "string",
    "InvestorID": "string",
    "ExchangeID": "char",
    "ProductID": "char",
    "SecurityType": "char",
    "SecurityID": "string",
    "BusinessClass": "char",
    "FeeByVolume": "double",
    "UpperRatio": "double",
}

CTORATstpSPQryOrderFundDetailField = {
    "InvestorID": "string",
    "SecurityID": "string",
    "ExchangeID": "char",
    "OrderSysID": "string",
    "BusinessUnitID": "string",
}

CTORATstpSPOrderFundDetailField = {
    "TradingDay": "string",
    "ExchangeID": "char",
    "OrderSysID": "string",
    "PbuID": "string",
    "OrderLocalID": "string",
    "SecurityID": "string",
    "AccountID": "string",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "TradeAmount": "double",
    "StampTaxFee": "double",
    "TransferFee": "double",
    "HandlingFee": "double",
    "RegulateFee": "double",
    "BrokerageFee": "double",
    "SettlementFee": "double",
    "Margin": "double",
    "OrderCashFrozen": "double",
    "TotalFeeFrozen": "double",
    "OrderAmount": "double",
    "Direction": "char",
}

CTORATstpSPQryFundTransferDetailField = {
    "AccountID": "string",
    "CurrencyID": "char",
    "TransferDirection": "char",
    "DepartmentID": "string",
}

CTORATstpSPFundTransferDetailField = {
    "FundSerial": "int",
    "ApplySerial": "int",
    "FrontID": "int",
    "SessionID": "int",
    "DepartmentID": "string",
    "AccountID": "string",
    "CurrencyID": "char",
    "TransferDirection": "char",
    "Amount": "double",
    "TransferStatus": "char",
    "OperateSource": "char",
    "OperatorID": "string",
    "OperateDate": "string",
    "OperateTime": "string",
    "StatusMsg": "string",
    "BankAccountID": "string",
    "BankID": "char",
}

CTORATstpSPQryPositionTransferDetailField = {
    "InvestorID": "string",
    "ShareholderID": "string",
    "SecurityID": "string",
    "TransferDirection": "char",
    "BusinessUnitID": "string",
    "PosiDirection": "char",
    "HedgeFlag": "char",
}

CTORATstpSPPositionTransferDetailField = {
    "PositionSerial": "int",
    "ApplySerial": "int",
    "FrontID": "int",
    "SessionID": "int",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "ExchangeID": "char",
    "ShareholderID": "string",
    "MarketID": "char",
    "PosiDirection": "char",
    "HedgeFlag": "char",
    "SecurityID": "string",
    "TradingDay": "string",
    "TransferDirection": "char",
    "TransferPositionType": "char",
    "HistoryVolume": "int",
    "TodayVolume": "int",
    "TransferStatus": "char",
    "OperatorID": "string",
    "OperateDate": "string",
    "OperateTime": "string",
    "StatusMsg": "string",
}

CTORATstpSPQryOrderActionField = {
    "InvestorID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "BusinessUnitID": "string",
    "PbuID": "string",
    "CancelOrderLocalID": "string",
    "OrderLocalID": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
}

CTORATstpSPOrderActionField = {
    "TradingDay": "string",
    "CancelOrderLocalID": "string",
    "ActionFrontID": "int",
    "ActionSessionID": "int",
    "OrderActionRef": "int",
    "OrderLocalID": "string",
    "OrderSysID": "string",
    "FrontID": "int",
    "SessionID": "int",
    "OrderRef": "int",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "OrderActionFlag": "char",
    "CancelOrderStatus": "char",
    "VolumeCanceled": "int",
    "StatusMsg": "string",
    "ErrorID": "int",
    "BranchID": "string",
    "PbuID": "string",
    "InsertUserID": "string",
    "InsertDate": "string",
    "InsertTime": "string",
    "InsertMillisec": "int",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "RequestID": "int",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "Mobile": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPQryStockPositionField = {
    "InvestorID": "string",
    "SecurityID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "BusinessUnitID": "string",
}

CTORATstpSPStockPositionField = {
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "TradingDay": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "HistoryPos": "int",
    "HistoryPosFrozen": "int",
    "TodayBSPos": "int",
    "TodayBSPosFrozen": "int",
    "TodayPRPos": "int",
    "TodayPRPosFrozen": "int",
}

CTORATstpSPQryLockField = {
    "InvestorID": "string",
    "SecurityID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "LockSysID": "string",
    "InsertTimeStart": "string",
    "InsertTimeEnd": "string",
    "BusinessUnitID": "string",
    "LockType": "char",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
}

CTORATstpSPQryExerciseField = {
    "InvestorID": "string",
    "SecurityID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "ExerciseSysID": "string",
    "InsertTimeStart": "string",
    "InsertTimeEnd": "string",
    "BusinessUnitID": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
}

CTORATstpSPQryLockPositionField = {
    "InvestorID": "string",
    "SecurityID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "BusinessUnitID": "string",
}

CTORATstpSPLockPositionField = {
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "TradingDay": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "Volume": "int",
    "FrozenVolume": "int",
    "HistoryPos": "int",
    "TodayBSPos": "int",
    "TodayPRPos": "int",
}

CTORATstpSPQryExerciseActionField = {
    "InvestorID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "BusinessUnitID": "string",
    "PbuID": "string",
    "CancelExerciseLocalID": "string",
    "ExerciseLocalID": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
}

CTORATstpSPExerciseActionField = {
    "TradingDay": "string",
    "BranchID": "string",
    "PbuID": "string",
    "CancelExerciseLocalID": "string",
    "ActionFrontID": "int",
    "ActionSessionID": "int",
    "ExerciseActionRef": "int",
    "ExerciseLocalID": "string",
    "ExerciseSysID": "string",
    "FrontID": "int",
    "SessionID": "int",
    "ExerciseRef": "int",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "ExerciseActionFlag": "char",
    "CancelOrderStatus": "char",
    "VolumeCanceled": "int",
    "StatusMsg": "string",
    "ErrorID": "int",
    "InsertUserID": "string",
    "InsertDate": "string",
    "InsertTime": "string",
    "InsertMillisec": "int",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "RequestID": "int",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "Mobile": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPQryLockActionField = {
    "InvestorID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "BusinessUnitID": "string",
    "PbuID": "string",
    "CancelLockLocalID": "string",
    "LockLocalID": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
}

CTORATstpSPLockActionField = {
    "TradingDay": "string",
    "BranchID": "string",
    "PbuID": "string",
    "CancelLockLocalID": "string",
    "ActionFrontID": "int",
    "ActionSessionID": "int",
    "LockActionRef": "int",
    "LockLocalID": "string",
    "LockSysID": "string",
    "FrontID": "int",
    "SessionID": "int",
    "LockRef": "int",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "LockActionFlag": "char",
    "CancelOrderStatus": "char",
    "VolumeCanceled": "int",
    "StatusMsg": "string",
    "ErrorID": "int",
    "InsertUserID": "string",
    "InsertDate": "string",
    "InsertTime": "string",
    "InsertMillisec": "int",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "RequestID": "int",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "Mobile": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPQryStockPositionTransferDetailField = {
    "InvestorID": "string",
    "ShareholderID": "string",
    "SecurityID": "string",
    "SPStockTransferReason": "char",
    "BusinessUnitID": "string",
    "TransferPositionType": "char",
}

CTORATstpSPStockPositionTransferDetailField = {
    "PositionSerial": "int",
    "ApplySerial": "int",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "ShareholderID": "string",
    "OuterInvestorID": "string",
    "OuterBusinessUnitID": "string",
    "OuterShareholderID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "SecurityID": "string",
    "TradingDay": "string",
    "SPStockTransferReason": "char",
    "TransferPositionType": "char",
    "HistoryVolume": "int",
    "TodayBSVolume": "int",
    "TodayPRVolume": "int",
    "TransferStatus": "char",
    "OperatorID": "string",
    "OperateDate": "string",
    "OperateTime": "string",
    "StatusMsg": "string",
    "StockPositionSerial": "int",
    "bRepeal": "int",
    "OriginPositionSerial": "int",
    "OperateSource": "char",
    "BizRef": "string",
}

CTORATstpSPQryTradingNoticeField = {
    "InvestorID": "string",
    "DateStart": "string",
    "DateEnd": "string",
    "TimeStart": "string",
    "TimeEnd": "string",
}

CTORATstpSPQryStockDisposalField = {
    "InvestorID": "string",
    "SecurityID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "StockDisposalSysID": "string",
    "InsertTimeStart": "string",
    "InsertTimeEnd": "string",
    "BusinessUnitID": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
}

CTORATstpSPQryStockDisposalActionField = {
    "InvestorID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "BusinessUnitID": "string",
    "PbuID": "string",
    "CancelStockDisposalLocalID": "string",
    "StockDisposalLocalID": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
}

CTORATstpSPStockDisposalActionField = {
    "TradingDay": "string",
    "BranchID": "string",
    "PbuID": "string",
    "CancelStockDisposalLocalID": "string",
    "ActionFrontID": "int",
    "ActionSessionID": "int",
    "StockDisposalActionRef": "int",
    "StockDisposalLocalID": "string",
    "StockDisposalSysID": "string",
    "FrontID": "int",
    "SessionID": "int",
    "StockDisposalRef": "int",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "StockDisposalActionFlag": "char",
    "CancelStockDisposalStatus": "char",
    "VolumeCanceled": "int",
    "StatusMsg": "string",
    "ErrorID": "int",
    "InsertUserID": "string",
    "InsertDate": "string",
    "InsertTime": "string",
    "InsertMillisec": "int",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "RequestID": "int",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "Mobile": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPQryCondOrderField = {
    "InvestorID": "string",
    "SecurityID": "string",
    "ExchangeID": "char",
    "ShareholderID": "string",
    "CondOrderID": "int",
    "InsertTimeStart": "string",
    "InsertTimeEnd": "string",
    "BusinessUnitID": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
}

CTORATstpSPCondOrderField = {
    "ExchangeID": "char",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "ShareholderID": "string",
    "SecurityID": "string",
    "Direction": "char",
    "OrderPriceType": "char",
    "OrderVolumeType": "char",
    "TimeCondition": "char",
    "VolumeCondition": "char",
    "MinVolume": "int",
    "ForceCloseReason": "char",
    "LimitPrice": "double",
    "VolumeTotalOriginal": "int",
    "CombOffsetFlag": "string",
    "CombHedgeFlag": "string",
    "CondOrderRef": "int",
    "AccountID": "string",
    "RequestID": "int",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "CondOrderID": "int",
    "TerminalInfo": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "ContingentCondition": "char",
    "ConditionPrice": "double",
    "PriceTicks": "int",
    "VolumeMultiple": "int",
    "RelativeFrontID": "int",
    "RelativeSessionID": "int",
    "RelativeParam": "string",
    "AppendContingentCondition": "char",
    "AppendConditionPrice": "double",
    "AppendRelativeFrontID": "int",
    "AppendRelativeSessionID": "int",
    "AppendRelativeParam": "string",
    "TradingDay": "string",
    "FrontID": "int",
    "SessionID": "int",
    "DepartmentID": "string",
    "CondOrderStatus": "char",
    "StatusMsg": "string",
    "InsertUserID": "string",
    "InsertDate": "string",
    "InsertTime": "string",
    "InsertMillisec": "int",
    "CancelTime": "string",
    "CancelUserID": "string",
    "ActiveTime": "string",
    "Operway": "char",
    "HDSerial": "string",
    "Mobile": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPQryCondOrderActionField = {
    "InvestorID": "string",
    "ExchangeID": "char",
    "ShareholderID": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
}

CTORATstpSPCondOrderActionField = {
    "ExchangeID": "char",
    "RequestID": "int",
    "CondOrderActionRef": "int",
    "CondOrderRef": "int",
    "FrontID": "int",
    "SessionID": "int",
    "CondOrderID": "int",
    "OrderActionFlag": "char",
    "SecurityID": "string",
    "CancelCondOrderID": "int",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "TerminalInfo": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "ShareholderID": "string",
    "InsertUserID": "string",
    "InsertDate": "string",
    "InsertTime": "string",
    "InsertMillisec": "int",
    "Operway": "char",
    "HDSerial": "string",
    "Mobile": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPQryInvestorLimitPositionField = {
    "InvestorID": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
}

CTORATstpSPInvestorLimitPositionField = {
    "InvestorID": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "TotalPositionLimit": "int",
    "LongPositionLimit": "int",
    "TodayBuyOpenLimit": "int",
    "TodaySellOpenLimit": "int",
    "TodayCoveredOpenLimit": "int",
    "TodayOpenLimit": "int",
    "LongCallPositionLimit": "int",
    "LongPutPositionLimit": "int",
    "LongUnderlyingPositionLimit": "int",
    "ShortUnderlyingPositionLimit": "int",
    "TotalPositionFrozen": "int",
    "LongPositionFrozen": "int",
    "TodayBuyOpenFrozen": "int",
    "TodaySellOpenFrozen": "int",
    "TodayCoveredOpenFrozen": "int",
    "TodayOpenFrozen": "int",
    "LongCallPositionFrozen": "int",
    "LongPutPositionFrozen": "int",
    "LongUnderlyingPositionFrozen": "int",
    "ShortUnderlyingPositionFrozen": "int",
}

CTORATstpSPQryInvestorLimitAmountField = {
    "InvestorID": "string",
    "ExchangeID": "char",
}

CTORATstpSPInvestorLimitAmountField = {
    "InvestorID": "string",
    "LongAmountLimit": "double",
    "LongAmountFrozen": "double",
    "MarketID": "char",
    "ExchangeID": "char",
}

CTORATstpSPQryCombOrderActionField = {
    "InvestorID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "BusinessUnitID": "string",
    "PbuID": "string",
    "CancelCombOrderLocalID": "string",
    "CombOrderLocalID": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
}

CTORATstpSPCombOrderActionField = {
    "TradingDay": "string",
    "BranchID": "string",
    "PbuID": "string",
    "CancelCombOrderLocalID": "string",
    "ActionFrontID": "int",
    "ActionSessionID": "int",
    "CombOrderActionRef": "int",
    "CombOrderLocalID": "string",
    "CombOrderSysID": "string",
    "FrontID": "int",
    "SessionID": "int",
    "OrderRef": "int",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "CombOrderActionFlag": "char",
    "CancelOrderStatus": "char",
    "VolumeCanceled": "int",
    "StatusMsg": "string",
    "ErrorID": "int",
    "InsertUserID": "string",
    "InsertDate": "string",
    "InsertTime": "string",
    "InsertMillisec": "int",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "RequestID": "int",
    "TerminalInfo": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "Mobile": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

CTORATstpSPQryCombOrderField = {
    "InvestorID": "string",
    "SecurityID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "CombOrderSysID": "string",
    "InsertTimeStart": "string",
    "InsertTimeEnd": "string",
    "BusinessUnitID": "string",
    "CombinationStrategy": "char",
    "CombDirection": "char",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
}

CTORATstpSPQryCombPositionField = {
    "InvestorID": "string",
    "SecurityID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "BusinessUnitID": "string",
    "CombinationStrategy": "char",
}

CTORATstpSPCombPositionField = {
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "TradingDay": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "CombinationStrategy": "char",
    "HistoryPos": "int",
    "HistoryPosFrozen": "int",
    "TodayPos": "int",
    "TodayPosFrozen": "int",
    "Margin": "double",
    "FrozenMargin": "double",
    "FrozenCommission": "double",
    "Commission": "double",
    "PrePosition": "int",
}

CTORATstpSPQryCombPosDetailField = {
    "InvestorID": "string",
    "CombSecurityID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "BusinessUnitID": "string",
    "CombinationStrategy": "char",
    "ExchangeCombID": "string",
    "CombinationStatus": "char",
}

CTORATstpSPCombPosDetailField = {
    "TradingDay": "string",
    "ExchangeCombID": "string",
    "CombinationStrategy": "char",
    "CombSecurityID": "string",
    "DepartmentID": "string",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "ExchangeID": "char",
    "HistoryPos": "int",
    "TodayPos": "int",
    "TradeDate": "string",
    "TradeTime": "string",
    "CombinationStatus": "char",
    "NoLegs": "int",
    "Leg1SecurityID": "string",
    "Leg1HistoryPos": "int",
    "Leg1TodayPos": "int",
    "Leg1PosiDirection": "char",
    "Leg1OptionsType": "char",
    "Leg2SecurityID": "string",
    "Leg2HistoryPos": "int",
    "Leg2TodayPos": "int",
    "Leg2PosiDirection": "char",
    "Leg2OptionsType": "char",
    "HistoryPosSplitFrozen": "int",
    "TodayPosSplitFrozen": "int",
    "Leg1HistoryPosSplitFrozen": "int",
    "Leg1TodayPosSplitFrozen": "int",
    "Leg2HistoryPosSplitFrozen": "int",
    "Leg2TodayPosSplitFrozen": "int",
}

CTORATstpSPQryExerciseAppointmentField = {
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "ExchangeID": "char",
    "ExerciseDay": "string",
    "PbuID": "string",
    "ShareholderID": "string",
    "AccountID": "string",
    "SecurityID": "string",
}

CTORATstpSPExerciseAppointmentField = {
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "ExchangeID": "char",
    "ExerciseDay": "string",
    "PbuID": "string",
    "ShareholderID": "string",
    "AccountID": "string",
    "CurrencyID": "char",
    "SecurityID": "string",
    "OptionsType": "char",
    "OptionUnit": "int",
    "UnderlyingSecurityID": "string",
    "ExerciseVolume": "int",
    "ExercisePrice": "double",
    "ExerciseDirection": "char",
    "CoverFlag": "char",
}

CTORATstpSPQryInsufficientCoveredStockPositionField = {
    "InvestorID": "string",
    "SecurityID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "BusinessUnitID": "string",
}

CTORATstpSPInsufficientCoveredStockPositionField = {
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "TradingDay": "string",
    "ExchangeID": "char",
    "SecurityID": "string",
    "TotalInsufficientVolume": "int",
    "PreFrozenVolume": "int",
    "RepaidVolume": "int",
}

CTORATstpSPQryCombSecurityField = {
    "CombSecurityID": "string",
    "ExchangeID": "char",
    "CombinationStrategy": "char",
}

CTORATstpSPCombSecurityField = {
    "ExchangeID": "char",
    "CombSecurityID": "string",
    "CombinationStrategy": "char",
    "Leg1SecurityID": "string",
    "Leg1SecurityName": "string",
    "RequiredLeg1PosiDirection": "char",
    "Leg2SecurityID": "string",
    "Leg2SecurityName": "string",
    "RequiredLeg2PosiDirection": "char",
}

CTORATstpSPQryCombExerciseField = {
    "InvestorID": "string",
    "CallSecurityID": "string",
    "PutSecurityID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "CombExerciseSysID": "string",
    "InsertTimeStart": "string",
    "InsertTimeEnd": "string",
    "BusinessUnitID": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
}

CTORATstpSPQryCombExerciseActionField = {
    "InvestorID": "string",
    "ExchangeID": "char",
    "MarketID": "char",
    "ShareholderID": "string",
    "BusinessUnitID": "string",
    "PbuID": "string",
    "CancelCombExerciseLocalID": "string",
    "CombExerciseLocalID": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
}

CTORATstpSPCombExerciseActionField = {
    "TradingDay": "string",
    "BranchID": "string",
    "PbuID": "string",
    "CancelCombExerciseLocalID": "string",
    "ActionFrontID": "int",
    "ActionSessionID": "int",
    "CombExerciseActionRef": "int",
    "CombExerciseLocalID": "string",
    "CombExerciseSysID": "string",
    "FrontID": "int",
    "SessionID": "int",
    "CombExerciseRef": "int",
    "InvestorID": "string",
    "BusinessUnitID": "string",
    "MarketID": "char",
    "ShareholderID": "string",
    "ExchangeID": "char",
    "CallSecurityID": "string",
    "PutSecurityID": "string",
    "ExerciseActionFlag": "char",
    "CancelOrderStatus": "char",
    "VolumeCanceled": "int",
    "StatusMsg": "string",
    "ErrorID": "int",
    "InsertUserID": "string",
    "InsertDate": "string",
    "InsertTime": "string",
    "InsertMillisec": "int",
    "InnerIPAddress": "string",
    "MacAddress": "string",
    "RequestID": "int",
    "TerminalInfo": "string",
    "BInfo": "string",
    "SInfo": "string",
    "IInfo": "int",
    "Operway": "char",
    "HDSerial": "string",
    "Mobile": "string",
    "OuterIPAddress": "string",
    "OuterPort": "int",
}

